### ISSUE TITLE
Should get this reviewed by smarter streams people

### ISSUE THREAD

**Issue by phated** [gulpjs/to-through#1]
Going to cc some stream people that are much better with streams than myself.  If you have time, please take a look at this and tell me if I'm insane.

@contra @terinjokes @mcollina @mafintosh @calvinmetcalf

**Comment by mcollina** [comment]
The biggest question is why. It's not clear what problems it solves for you.

**Comment by phated** [comment]
Gulp provides it's 2 stream APIs as Readable/Transform or Writeable/Transform streams. I've also created a module called "sink" that handles the Writeable/Transform that Chris Dickinson helped me with awhile ago and this is the other side of it.

**Comment by mcollina** [comment]
Rather using `nextTick` to start flushing the data, I would listen to the `'newListener'` event, as in here https://github.com/mcollina/cloneable-readable/blob/master/index.js#L86-L98, to detect when the stream is piped. `nextTick` is a _very bad trick_, and I think we should use it only if there is no other alternatives.

If I understand what I see in the code, it first let anything that is coming from its upstream flow, and then it attach everything that comes from the readable. Is this correct? Maybe it should be noted in the README.

**Comment by phated** [comment]
@mcollina I'm not totally sure how I can use `newListener` to know if it's being used as a Readable vs Transform but I'll experiment.

I currently document that in the API but maybe not clearly enough.

**Comment by phated** [comment]
I think this is about as done as it will get.  Thanks again @mcollina
