### ISSUE TITLE
Convert to Streamx

### ISSUE THREAD

**Issue by phated** [gulpjs/to-through#7]
This currently uses through2, but it should use streamx in the next major release.

**Comment by phated** [comment]
@coreyfarrell going to assign you here, too. Mostly just because I know you've kicked the streamx tires a bit.

**Comment by coreyfarrell** [comment]
This works, I have a local branch I was working on just need to retest with updated streamx now that we're on the updated scaffolding.

**Comment by phated** [comment]
Don't forget to pull the prettier changes the CI just pushed!
